### ISSUE TITLE
Weird Bug with this github project page

### ISSUE THREAD

**Issue by jgarte** [out-of-cheese-error/the-way#103]
For some reason this github page is always very slow when I try to navigate it.

Does this happen for anyone else?

**Comment by Ninjani** [comment]
Hmm, this is probably because of the SVGs. I've made them a bit smaller now, any change?

**Comment by jgarte** [comment]
I notice a slight difference but it is still unbearably slow. 

I'm still getting stuck trying to scroll down.

**Comment by Ninjani** [comment]
Okay, I've replaced the SVGs with PNGs linking to the respective asciinema casts - should be fixed now?

**Comment by jgarte** [comment]
> Okay, I've replaced the SVGs with PNGs linking to the respective asciinema casts - should be fixed now?

The project page scrolls as smooth as butter now! 🧈
