### ISSUE TITLE
Editing a snippet in an editor

### ISSUE THREAD

**Issue by tpoliaw** [out-of-cheese-error/the-way#104]
When editing an existing snippet (`the-way search -> select -> shift+right`), after confirming the other fields, the prompt says `Code snippet (<RET> to edit in external editor)`. What is `<RET>` in this case? Return/enter appears to only submit the snippet as it is. 

I have tried with `$EDITOR` both unset and set to `vi`.

**Comment by tpoliaw** [comment]
Been looking at this again and it only behaves like this if the command/snippet is a single line. Happy to submit a PR for this but not sure what the preferred behaviour would be.

Options I can think of:
* Open the editor for all snippets immediately instead of using the prompt (keep the prompt for the other fields)
* Open the editor with the original command if  you delete the contents of a single line command. Potentially more convenient for single line commands but a bit unintuitive
* Change the prompt to only mention editor when there are multiple lines (but keep the behaviour the same)
* Something else?

**Comment by Ninjani** [comment]
Ah yes, good point, it's not super obvious now. I personally would prefer option 3 
> Change the prompt to only mention editor when there are multiple lines (but keep the behaviour the same)

since spinning up an editor for a single line command seems unnecessary in most cases - but let me know if you think otherwise or there are cases I'm not thinking of where editor support would be useful.

**Comment by Ninjani** [comment]
Another alternative would be to use a different key combo (Shift-Enter for instance) to open up the editor in this case - so would need a change in the prompt and behaviour.

**Comment by tpoliaw** [comment]
The only issue I can see is if you want to add a second line to a single line command. Not sure how common a use case that is though. How easy is it to handle key-combos from Dialoguer? I think that would be the best of both worlds but is probably  the most involved change.

**Comment by Ninjani** [comment]
> if you want to add a second line to a single line command

Oh this is a great point, hadn't considered it. Also, looks like dialoguer has some issues with certain characters (e.g. [#128](https://github.com/mitsuhiko/dialoguer/issues/128)) so I think your Option 1 ( Open the editor for all snippets immediately instead of using the prompt ) makes the most sense now, even if it is a bit cumbersome for single line snippets.

Would you be up for making a PR?

**Comment by tpoliaw** [comment]
Sure, will have a look this evening.
> a bit cumbersome for single line snippets.

Thinking about this, would a fourth option be to prompt for `edit snippet [y/N]?`? Given edit also lets you edit the other metadata, it's not unlikely that the only edit is to change tag/description and this would prevent the editor opening every time which may be slow (can `$EDITOR` be set to a GUI app?).

**Comment by Ninjani** [comment]
> Thinking about this, would a fourth option be to prompt for edit snippet [y/N]??

Yep, I like this idea! And yeah EDITOR could be anything so it's a pretty good way to make sure you don't open it unless you want to.
