### ISSUE TITLE
Bug: Couldn't find language .txt in the list of extensions, defaulting to .txt

### ISSUE THREAD

**Issue by jgarte** [out-of-cheese-error/the-way#121]
```
✔ Language · .txt
Couldn't find language .txt in the list of extensions, defaulting to .txt
```

**Comment by Ninjani** [comment]
Hmm, Language in that case would be "text" and not the extension. The extension is auto-derived from the language name

**Comment by jgarte** [comment]
Thanks for the reply! 

So, it's not a bug but as intended? Not sure I fully understood.

**Comment by Ninjani** [comment]
Yes, I'd say it's as intended as the language inputted should be the name of the language and not the extension
