### ISSUE TITLE
--stdout short flag -s or use standard output as the default instead of the clipboard

### ISSUE THREAD

**Issue by jgarte** [out-of-cheese-error/the-way#122]
Hi,

What do you think of having a short flag for `--stdout`? 

I'd prefer to just have to type `-s` or any other single character to specify standard output.

I'd also prefer for standard output to be the default instead of clipboard.

WDYT?

**Comment by Ninjani** [comment]
Sure, I'll add `-s`. Not sure about the having stdout as default, I use clipboard more often and using stdout would only make sense in combination with a different command (such as the shell variants [here](https://github.com/out-of-cheese-error/the-way#shell-commands)).

**Comment by jgarte** [comment]
The reason it benefits me to have standard output as the default is because I'm using the text editor [vis](https://github.com/martanne/vis) which allows me to easily pipe text into the editor with the `<`, and `|`, [operators](https://github.com/martanne/vis/wiki/Differences-from-Kakoune).

For example I could run something like the following in vis' command mode to give a quick contrived example:

`:<ls -a`
