### ISSUE TITLE
WSL2 support

### ISSUE THREAD

**Issue by wisewtf** [out-of-cheese-error/the-way#134]
Hello,

I know Windows is not supported yet. But I tried to make it work on WSL2 nonetheless. 

I'm stuck on this issue:

```bash
> the-way cp 2
openssl x509 -noout -text -in
Error: Can't open display: (null)
Snippet #2 copied to clipboard
```

This happens every time `the-way` tries to copy stuff to the SYSTEM clipboard. I'm assuming it's because wsl2 cannot do it natively. WSL2 can use Windows binaries tho, as specified [here](https://www.raymondcamden.com/2017/10/19/copying-to-clipboard-with-windows-subsystem-for-linux)

I am unsure why it tries to use a display. I hope anyone can shed some light about this.

`search` seems to work properly. Altough with the `cmdsave` function, I get the same issue after I use search.

```bash
❯ the-way search
find <path> -name <file>
✔ path · .
✔ file · '*.a'
Error: Can't open display: (null)
Snippet #1 copied to clipboard
```

Please let me know if you need further testing.

**Comment by Ninjani** [comment]
Hi, thanks for the issue and testing.

Are you using the default copy command in the config? You should be able to see this in the copy_cmd field in the config file stored at `the-way config get`. You may have to change this to the command in the link you mentioned - the default for linux is xclip (also described [here](https://github.com/out-of-cheese-error/the-way#copy-command)) which would explain the error message. 

Let me know if that works out, I don't currently have access to a Windows machine to check but I can find one if it doesn't

**Comment by wisewtf** [comment]
I am using the default configuration.

```toml
theme = 'base16-ocean.dark'
db_dir = '/home/wise/.local/share/the-way/the_way_db'
themes_dir = '/home/wise/.local/share/the-way/themes'
copy_cmd = 'xclip -in -selection clipboard'
```

I was about ready to apologize because I was able to make it work **ONCE** on my main desktop computer which is running the Windows Terminal Preview version on Windows 11, and earlier I tried on my work latop which has stable Windows Terminal and Windows 10.

After the first try with `the-way cp 1`, which put the snippet in the clipboard and I was actually able to paste it around... it stopped working.

All I did was try to create a snippet with variables and copy that from the search function. It COMPLETELY freezes the terminal and Windows doesn't even realize it is, it's like it's absolutely stuck. 

So I thought it could be an issue with variables in snippets, but trying to replicate the first result didn't work either. Windows Terminal just freezes.

So... `clip.exe` works. I just can't figure out what you mean with 'you could make a file with `echo "${1:-/dev/stdin}" | clip.exe`. 

You mean make an executable script with `echo "${1:-/dev/stdin}" | clip.exe` as contents and use the script's path as the configuration for `copy_cmd` ? Or do I have to just write a simple file with those contents and put that path in? or do I have to `cat` that file in the `copy_cmd` field?

**Comment by Ninjani** [comment]
Yeah I'm not super familiar with WSL2 but I don't think using xclip can work, the xwindow would need to be connected to Windows. 

And yes, I meant an executable as you tried. It's just meant to take what's in stdin, echo it, and then pipe that to clip.exe (since for some reason clip.exe doesn't work without the pipe, as in `clip.exe stuff_to_copy` doesn't work) - is there a different way to define stdin on WSL2?

**Comment by Ninjani** [comment]
Had a chance to try it out on WSL2 - this should work:
make a script with 
```sh
#!/bin/sh
echo "$(cat -)" | clip.exe
```
and set copy_cmd to ./myscript

**Comment by wisewtf** [comment]
Yep!

Works perfectly. Thank you very much for the support. This can be closed!
