### ISSUE TITLE
ZSH completion panics

### ISSUE THREAD

**Issue by numkem** [out-of-cheese-error/the-way#135]
Hello,

Running `the-way complete zsh` on the latest version `0.17.0` crashes the application with this error message:

```
The application panicked (crashed).
Message:  Fatal internal error. Please consider filing a bug report at https://github.com/clap-rs/clap/issues
Location: /build/the-way-0.17.0-vendor.tar.gz/clap/src/completions/zsh.rs:346
```

This was built using rust 1.61 on NixOS.

**Comment by Ninjani** [comment]
Should be fixed in 0.17.1, please reopen if not!
