### ISSUE TITLE
sync from gist to local bug

### ISSUE THREAD

**Issue by c-hui** [out-of-cheese-error/the-way#143]
After synced from gist to local in a new server, local index is not updated. So when new a snippet, will replace exited one.
![image](https://user-images.githubusercontent.com/27413785/212022890-1bdab801-31cd-4e7b-b49c-0a1316633b50.png)

**Comment by c-hui** [comment]
谢谢，来信已收到！

**Comment by Ninjani** [comment]
Fixed in v0.19.0, thanks!

**Comment by Niko72** [comment]
I have the same issue but with the newest version 0.19.1
