### ISSUE TITLE
sync from gist to local bug

### ISSUE THREAD

**Issue by Niko72** [out-of-cheese-error/the-way#145]
I have the same [issue](https://github.com/out-of-cheese-error/the-way/issues/143) (closed) but now with the newest version 0.19.1

**Comment by Ninjani** [comment]
Can you give me some steps to reproduce? `the-way sync gist` in a new server and then `the-way add` causes the gist snippet to be replaced?

**Comment by Niko72** [comment]
Are you sure the command `the-way add` exists? I got: `error: unrecognized subcommand 'add' ` I am a new user and add new commands with `the-way cmd` and the sync with `the-way sync date` or `the-way sync local` or `the-way sync gist`. With a new server and only one client. Nothing helped. It just overwrites some existing commands with existing `#`. I will post an example when I am back at home. Thanks for your support!

**Comment by Ninjani** [comment]
Apologies, I meant `the-way new`. I think I've found the issue, would you be able to test with the PR branch?

**Comment by Niko72** [comment]
Sorry, I would like to help, but I don't know how to test it with the PR branch.

**Comment by Ninjani** [comment]
Okay, no worries, I'll make a new release and you can reopen this issue if the problem persists

**Comment by Ninjani** [comment]
Should be fixed in v0.19.2, I'll reopen for now in case it isn't.
