### ISSUE TITLE
Cannot add new syntax files

### ISSUE THREAD

**Issue by chopfitzroy** [out-of-cheese-error/the-way#152]
I am trying to run the following command:

```bash
the-way themes language ~/zola/sublime/syntaxes/extra/TypeScript.sublime-syntax
```

And I get the following output:

```
Error:
   0: SyntaxError: "~/zola/sublime/syntaxes/extra/TypeScript.sublime-syntax"

Suggestion: Couldn't load a syntax from ~/zola/sublime/syntaxes/extra/TypeScript.sublime-syntax, are you sure this is a valid .sublime-syntax file with a 'name' key?
```

I took a look at the [syntect](https://github.com/trishume/syntect/) docs as well as the [syntax definitions page for Sublime Text 3](https://www.sublimetext.com/docs/syntax.html) and from what I can see these are formatted correctly.

Is there something I am missing?

**Comment by Ninjani** [comment]
This was because of an older fancy-regex version that didn't have support for \G (https://github.com/trishume/syntect/issues/454). Should be fixed now
