### ISSUE TITLE
stdout option breaks in the latest releases

### ISSUE THREAD

**Issue by SmartFinn** [out-of-cheese-error/the-way#159]
Since upgrading to v0.20.1 the `--stdout` option of `search` command stop working as expected. Instead, the option does nothing. It just copies the snippet to clipboard like the option didn't pass.

![image](https://github.com/out-of-cheese-error/the-way/assets/819186/6149870a-5f4d-435d-91d4-ebef474f2f3d)

This also breaks `cmdsearch` function in [Shell commands](https://github.com/out-of-cheese-error/the-way#shell-commands).

**Comment by Ninjani** [comment]
Yep, the stdout and exact options got mixed up, thanks for the report. Should be fixed in v0.20.2

**Comment by SmartFinn** [comment]
Thanks for the quick fix. Now it works as expected.
