### ISSUE TITLE
config giving error

### ISSUE THREAD

**Issue by muralikodali** [out-of-cheese-error/the-way#41]
the-way config default producing no output and giving following error.
Error: 
   0: Failed to read configuration file.

**Comment by Ninjani** [comment]
This sounds like it could be a permissions error for the default config location. I've made some fixes in #42 that 
1. should allow for running `the-way config default` so you can generate a default config and then change the location of the config file with `export THE_WAY_CONFIG=<path/to/new_config_file.toml>`. 
2. Throws a more helpful error if the config file can't be read and gives instructions on fixing it.

I'll push a new release once the tests pass, thanks for bringing it to my attention!

**Comment by Ninjani** [comment]
I've made a new release ([cargo](https://crates.io/crates/the-way/0.2.4), [binaries](https://github.com/out-of-cheese-error/the-way/releases/tag/v0.2.4)). Can you see if this resolves your issue?

**Comment by muralikodali** [comment]
Thanks. updated binary now works flawless. 
config file is now  located in ~/.config/the-way/the-way.toml and other directories are placed in ~/.local/share.
$ the-way config default  also directed output to terminal
