### ISSUE TITLE
Documentation: Theme format?

### ISSUE THREAD

**Issue by daturkel** [out-of-cheese-error/the-way#47]
I see there's a folder to put themes in, but I can't seem to figure out what format a theme file should look like. Could this be documented somewhere?

**Comment by Ninjani** [comment]
Good idea. Theme files need to be in the [.tmTheme](https://www.sublimetext.com/docs/3/color_schemes_tmtheme.html) format. Searching GitHub for [.tmTheme](https://github.com/search?q=.tmTheme) pulls up some examples. I've added this to the README and a little more clarification to `the-way theme add -h`.

**Comment by daturkel** [comment]
Just added a theme and it worked perfectly, thanks!
