### ISSUE TITLE
Snippets are sorted alphabetically, not numerically

### ISSUE THREAD

**Issue by daturkel** [out-of-cheese-error/the-way#65]
If you have more than 9 snippets, then `the-way search` lists them in alphabetical order, rather than numerical order.

e.g.

```
1
10
11
12
2
3
4
...
```

<img width="303" alt="Screen Shot 2020-07-22 at 7 21 45 PM" src="https://user-images.githubusercontent.com/1828387/88238821-b8e9c700-cc50-11ea-88ad-e2b39b50233e.png">

**Comment by Ninjani** [comment]
Should be fixed in v0.6.1!

**Comment by daturkel** [comment]
works perfectly, thanks!
