### ISSUE TITLE
Unsupported: cannot change the io buffer size across restarts

### ISSUE THREAD

**Issue by numkem** [out-of-cheese-error/the-way#67]
Running any commands gives me this error: `Unsupported: cannot change the io buffer size across restarts. please change it back to 8388608`.

I've tried deleting `~/.config/the-way` to no avail. This is version `0.7.0` on NixOS.

Running the same command with backtrace set to `full` gives:
```
Error: 
   0: Unsupported: cannot change the io buffer size across restarts. please change it back to 8388608

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: color_eyre::config::HookBuilder::install::{{closure}}::h89493c7b19a69a32
      at <unknown source file>
   2: the_way::the_way::TheWay::start::hea72f08e14a0d57d
      at <unknown source file>
   3: the_way::main::ha4dc93d41b39356d
      at <unknown source file>
   4: std::rt::lang_start::{{closure}}::hf19916ed3db71252
      at <unknown source file>
   5: std::rt::lang_start_internal::h7d1b27a1580794aa
      at <unknown source file>
   6: main
      at <unknown source file>
   7: __libc_start_main
      at <unknown source file>
   8: _start
      at <unknown source file>
```

Thanks!

**Comment by Ninjani** [comment]
Hmm, this could be because of the version change - have you done the database migration as described in the [release](https://github.com/out-of-cheese-error/the-way/releases/tag/v0.7.0)?  You'll have to download the older version and then run
```bash
the-way export snippets.json
the-way clear
```
then get the latest version and import with
```bash
the-way import snippets.json
```
Let me know how it goes!

**Comment by numkem** [comment]
I can't run

**Comment by Ninjani** [comment]
With the older version as well? The one that worked previously (0.6)?

**Comment by numkem** [comment]
I did do an export a while ago.

I had to delete both `~/.config/the-way` and `~/.local/share/the-way` for the error to go away.

Thanks!

**Comment by Ninjani** [comment]
Okay, that's odd but glad you found a way! Will keep an eye out for this in the `sled` repository. Thanks!
