### ISSUE TITLE
Replace copy_to_clipboard code with arboard

### ISSUE THREAD

**Issue by Ninjani** [out-of-cheese-error/the-way#76]
[arboard](https://github.com/ArturKovacs/arboard) seems to do the right thing when it comes to X11 clipboard handling. Should allow replacing the current very ugly xclip/pbcopy hack in `utils.rs`. Also, replacing clipboard with arboard in `tests/cli.rs` should allow copy tests to run on Linux CI as well, which is ideal.

**Comment by jonasmalacofilho** [comment]
I started to work on this, just for fun, but I'm having some problems getting unrelated tests to pass, even before any changes:

```

failures:

---- add_two_cmd_snippets stdout ----
thread 'add_two_cmd_snippets' panicked at 'assertion failed: add_two_cmd_snippets_rexpect(config_file).is_ok()', tests/cli.rs:231:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- change_snippet stdout ----
thread 'change_snippet' panicked at 'assertion failed: change_snippet_rexpect(config_file).is_ok()', tests/cli.rs:240:5

---- add_two_snippets stdout ----
thread 'add_two_snippets' panicked at 'assertion failed: add_two_snippets_rexpect(config_file).is_ok()', tests/cli.rs:222:5
```

Additionally, the `change_snippet` test does not appear to be deterministic, and only sometimes fails.

Do you have any idea of what may be going on?  Is there some special setup that I need first?  I'm having a hard time understanding how these tests work, so I'm haven't been able to figure out what's missing.

---

Back to the clipboard issue itself, the changes are very straightforward, but I noticed and just reported a small issue with arboard on Linux (ArturKovacs/arboard#4).

**Comment by Ninjani** [comment]
Hi, thanks for looking into this! The tests need to be run with a single thread (`cargo test -- --test-threads=1`) since the same environment variable is changed separately for each test. I'll add a contributing file with this info.

**Comment by jonasmalacofilho** [comment]
I figured this could be it but, err, got the options wrong and was trying `--jobs` :facepalm:

**Comment by Ninjani** [comment]
Haha yeah `cargo test` has an unbelievable number of options

**Comment by tpoliaw** [comment]
Doesn't look like there's much happening here for the last year, @jonasmalacofilho, are you still on this?
Was there a reason for choosing `arboard` over the more widely used `copypasta` fork of rust-clipboard?

**Comment by Ninjani** [comment]
> Was there a reason for choosing arboard over the more widely used copypasta fork of rust-clipboard?

So with `copypasta` there's this issue (or expected behavior I suppose) that clipboard contents are cleared after the program exits (https://github.com/alacritty/copypasta/issues/5). `arboard` solves this without the need for integrating another clipboard manager.

An additional point to add to this issue is Android support - right now it's done with `termux-clipboard-set`, would be nice to keep this while changing the others to `arboard`

**Comment by Jarsop** [comment]
Hello, I would like to work on this issue but it seems that the maintainer of `arboard` plans to stop maintaining this repository soon and archive it. Do you have any ideas/preferences for a replacement ?

**Comment by Ninjani** [comment]
Thanks @Jarsop. It seems like there won't be a one size fits all library here so maybe it makes most sense to continue the way it is now and shell out to external programs.

 In that case, the program used should be a config variable (as requested [here](https://github.com/out-of-cheese-error/the-way/pull/109#issuecomment-986140445)) and should support xclip, pbcopy, xsel, termux-clipboard-set, and wl-copy for now. Would be good if it's organized in a way that makes it easy to add more such programs if people request them. 

Thoughts?

**Comment by Jarsop** [comment]
I suggest adding an array of `CopyWrapper` structures that could be selected by a variable in the configuration file. What do you think about it?

**Comment by Ninjani** [comment]
Yes, sounds good. The default value can be set using conditional compilation on the detected OS (so [these lines](https://github.com/out-of-cheese-error/the-way/blob/d586d3cafb2b9ebdb8319c7960cc7645004b17e9/src/utils.rs#L26) would move [here](https://github.com/out-of-cheese-error/the-way/blob/d586d3cafb2b9ebdb8319c7960cc7645004b17e9/src/configuration.rs#L39))

**Comment by Jarsop** [comment]
Yes we are aligned :)

**Comment by Jarsop** [comment]
I have a first implementation [here](https://github.com/Jarsop/the-way/tree/feat/improve_copy_to_clipboard). If you have any suggestions, they are welcome.
