### ISSUE TITLE
Import from Gist

### ISSUE THREAD

**Issue by Ninjani** [out-of-cheese-error/the-way#77]
Expand `the-way import` to allow importing snippets from public Gists (keep link to original gist in description / tags). There's already a `get_gist` function in `gist.rs` which returns a gist with a description, a link, and a set of files each having their language and code content.

**Comment by xiaochuanyu** [comment]
I'd like to give this a try.

**Comment by xiaochuanyu** [comment]
I assume this feature should not require Github access token?
`GistClient` currently requires it.

**Comment by Ninjani** [comment]
Hey, thanks for looking into it! It's true that importing from public gists doesn't need the token but importing your own private gists would still need it. So I think a good solution is to make the token an `Option` in `GistClient` and throw an error if the user tries to sync or import a private token without it. What do you think?
