### ISSUE TITLE
Sync Error

### ISSUE THREAD

**Issue by johnhayesio** [out-of-cheese-error/the-way#86]
Tried using the-way sync and pasting the Github token with gists enabled, but getting this returned:

Error:
   0: SyncError: "422 {\"message\":\"Validation Failed\",\"errors\":[{\"resource\":\"Gist\",\"code\":\"missing_field\",\"field\":\"files\"}],\"documentation_url\":\"https://docs.github.com/v3/gists/#create-a-gist\"}"

Suggestion: Make sure your GitHub access token is valid.
Get one from https://github.com/settings/tokens/new (add the "gist" scope).
Set it to the environment variable $THE_WAY_GITHUB_TOKEN

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

Also added the token into a env var as suggested, but same error is thrown.

**Comment by Ninjani** [comment]
I could replicate this when trying to sync without having any snippets stored - is it the same situation for you or do you have some snippets and it's still throwing this error? 

I've made a fix that prints "No snippets to sync." instead of this error, it'll be in the next release later today.

**Comment by johnhayesio** [comment]
Alright, so I didn't have any snippets added. I went ahead and added a couple before trying to sync as can be seen here: https://share.getcloudapp.com/12urggz8. After adding the snippets, I then ran the-way sync again adding in the token and was given this error: https://share.getcloudapp.com/2NujzzNG. I also tried adding the env var to my zshrc file again, but got the same error.

**Comment by Ninjani** [comment]
Yes, this error I'm familiar with and is fixed ([3d8d0c3](https://github.com/out-of-cheese-error/the-way/commit/3d8d0c39b0c998c5cd042c4820404dd1fccee6ca)) on master. I'll make a new release now, let me know if that fixes it!

**Comment by Ninjani** [comment]
Okay, new release is out ([here](https://github.com/out-of-cheese-error/the-way/releases/tag/v0.11.0)). Could you try it out? You'll need to export and re-import as written in the release notes.

**Comment by johnhayesio** [comment]
Everything is cleared up on my end now. Thanks a ton!
