### ISSUE TITLE
Panic if xclip is not installed

### ISSUE THREAD

**Issue by tpoliaw** [out-of-cheese-error/the-way#89]
Trying to copy a snippet without xclip being installed leads to a panic
```
`❯ the-way search     
The application panicked (crashed).
Message:  Clipboard Error: 
   0: No such file or directory (os error 2)
Location: /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/the-way-0.11.1/src/the_way/snippet.rs:259
```
 Installing xclip solves the problem but required reading through the source to figure out. Would it be useful to add a probable cause to the expect error? Something like 'Clipboard Error - is xclip available?' would give users a clue what's up.

**Comment by Ninjani** [comment]
Good idea! Would also make sense to add it to the README as a requirement. It uses `pbcopy` on MacOS and `xclip` on Linux. I'm hoping to switch instead to a rust clipboard library (Issue #76) but haven't had a chance to test it out yet.

Would you like to make a PR or shall I?

**Comment by tpoliaw** [comment]
I'll have a look if you like. If the clipboard app is os dependent, would it make sense to add the message to the ClipboardError instead of the unwrap?

Also, slightly off topic but LostTheWay is an amazing Error name for this crate.

**Comment by Ninjani** [comment]
> I'll have a look if you like. If the clipboard app is os dependent, would it make sense to add the message to the ClipboardError instead of the unwrap?

Thanks! Yep, adding the message to ClipboardError makes the most sense and would be pretty easy to clean up if/when the switch to another crate happens.


> Also, slightly off topic but LostTheWay is an amazing Error name for this crate.

The one case where naming was easy!
